import 'dart:async';

import 'package:flutter/material.dart';

import 'package:flutter_oklyn_mobile/core/di/service_locator.dart';
import 'package:flutter_oklyn_mobile/features/master_product/domain/entities/master_product.dart';
import 'package:flutter_oklyn_mobile/features/master_product/domain/usecases/master_product_usecase.dart';
import 'package:flutter_oklyn_mobile/features/master_product/presentation/utils/failure_text.dart';
import 'package:flutter_oklyn_mobile/features/master_product/presentation/widgets/tag_chips_input.dart';
import 'package:flutter_oklyn_mobile/shared/themes/app_colors.dart';

/// Master registration name (auto, read-only) + tag pool inline edit panel
/// on the master detail screen — FEATURE_2609_80 / 07.
///
/// **File**: lib/features/master_product/presentation/widgets/master_tags_panel.dart
/// **Web original**: `master-products/[id]/components/MasterTagsPanel.tsx` @09208a0
///
/// Tags are the master pool (+ channel raw, combined at push time). Saving an
/// empty list (= remove all) is allowed. Initial values come from the parent
/// [master]; save (M20) notifies [onSaved] only.
///
/// ❌ The registration name is generated by rule — never editable here.
/// ❌ Draws no card shell or title — the detail page wraps it (09).
class MasterTagsPanel extends StatefulWidget {
  final MasterProduct master;
  final ValueChanged<MasterProduct> onSaved;

  const MasterTagsPanel({
    required this.master,
    required this.onSaved,
    super.key,
  });

  @override
  State<MasterTagsPanel> createState() => _MasterTagsPanelState();
}

class _MasterTagsPanelState extends State<MasterTagsPanel> {
  final MasterProductUseCase _useCase = getIt<MasterProductUseCase>();

  bool _isEditing = false;
  List<String> _tags = [];
  bool _isSaving = false;
  String _error = '';
  bool _saved = false;
  Timer? _savedTimer;

  @override
  void initState() {
    super.initState();
    _tags = [...widget.master.tags];
  }

  @override
  void dispose() {
    _savedTimer?.cancel();
    super.dispose();
  }

  void _startEdit() {
    setState(() {
      _tags = [...widget.master.tags];
      _error = '';
      _saved = false;
      _isEditing = true;
    });
  }

  Future<void> _handleSave() async {
    setState(() {
      _isSaving = true;
      _error = '';
      _saved = false;
    });
    final result = await _useCase.updateMasterTags(widget.master.id, _tags);
    if (!mounted) {
      return;
    }
    result.fold(
      (failure) => setState(() {
        _error = failureText(failure, '태그 저장에 실패했습니다.');
        _isSaving = false;
      }),
      (patched) {
        setState(() {
          _isEditing = false;
          _saved = true;
          _isSaving = false;
        });
        // Transient confirmation — auto-dismiss.
        _savedTimer?.cancel();
        _savedTimer = Timer(const Duration(milliseconds: 2500), () {
          if (mounted) {
            setState(() => _saved = false);
          }
        });
        widget.onSaved(patched);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final currentTags = widget.master.tags;
    final labelStyle = TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w500,
      color: scheme.onSurfaceVariant,
    );
    final hintStyle = TextStyle(fontSize: 12, color: scheme.onSurfaceVariant);
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (_error.isNotEmpty) ...[
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: scheme.errorContainer,
                borderRadius: BorderRadius.circular(4),
              ),
              child: Text(
                _error,
                style: TextStyle(fontSize: 14, color: scheme.error),
              ),
            ),
            const SizedBox(height: 12),
          ],
          Text('등록상품명 (자동)', style: labelStyle),
          const SizedBox(height: 4),
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: BoxDecoration(
              color: scheme.surfaceContainerLow,
              borderRadius: BorderRadius.circular(4),
            ),
            child: Text(
              widget.master.registrationName ?? '옵션·구성상품 설정 후 자동 생성됩니다',
              style: const TextStyle(fontSize: 14),
            ),
          ),
          const SizedBox(height: 4),
          Text('옵션/구성상품에서 규칙으로 생성됩니다 — 마켓 전송용.', style: hintStyle),
          const SizedBox(height: 16),
          Text('태그 (마스터 풀)', style: labelStyle),
          const SizedBox(height: 4),
          if (_isEditing) ...[
            TagChipsInput(
              tags: _tags,
              onChanged: (next) => setState(() => _tags = next),
              disabled: _isSaving,
            ),
            const SizedBox(height: 4),
            Text(
              'Enter 또는 콤마로 추가하세요.',
              style: TextStyle(fontSize: 11, color: scheme.onSurfaceVariant),
            ),
          ] else if (currentTags.isEmpty)
            Text(
              '등록된 태그가 없습니다.',
              style: TextStyle(fontSize: 14, color: scheme.onSurfaceVariant),
            )
          else
            Wrap(
              spacing: 6,
              runSpacing: 6,
              children: [
                for (final tag in currentTags)
                  Container(
                    padding:
                        const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                    decoration: BoxDecoration(
                      color: scheme.surfaceContainerHighest,
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Text(tag, style: const TextStyle(fontSize: 14)),
                  ),
              ],
            ),
          const SizedBox(height: 4),
          Text('채널별 태그는 셀의 [태그 편집]에서 조정하세요.', style: hintStyle),
          if (_saved && _error.isEmpty) ...[
            const SizedBox(height: 12),
            const Text(
              '태그를 저장했습니다.',
              style: TextStyle(
                fontSize: 14,
                color: AppColors.successForeground,
              ),
            ),
          ],
          const SizedBox(height: 12),
          if (_isEditing)
            Wrap(
              spacing: 8,
              runSpacing: 8,
              crossAxisAlignment: WrapCrossAlignment.center,
              children: [
                FilledButton(
                  onPressed: _isSaving ? null : _handleSave,
                  child: _isSaving
                      ? const _BusyLabel('저장 중...')
                      : const Text('저장'),
                ),
                OutlinedButton(
                  onPressed: _isSaving
                      ? null
                      : () => setState(() {
                            _isEditing = false;
                            _error = '';
                          }),
                  child: const Text('취소'),
                ),
              ],
            )
          else
            OutlinedButton(onPressed: _startEdit, child: const Text('수정')),
        ],
      ),
    );
  }
}

/// Spinner + label (web `<Spinner label=… />`).
class _BusyLabel extends StatelessWidget {
  final String label;

  const _BusyLabel(this.label);

  @override
  Widget build(BuildContext context) => Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          const SizedBox(
            width: 16,
            height: 16,
            child: CircularProgressIndicator(strokeWidth: 2),
          ),
          const SizedBox(width: 4),
          Text(label),
        ],
      );
}
